language: java
jdk:
  - openjdk15

sudo: false

install: true

script: mvn clean package -DskipTests=true

services:
  - postgresql

before_install:
  - psql -c 'create database forum;' -U postgres

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      oggen18@gmail.com
    on_success: never
    on_failure: always

env:
  global:
    - CODECOV_TOKEN="f4e6786c-51bb-4cdb-b42c-6a65623e46fd"
deploy:
  provider: heroku
  api_key:
    secure: 13m2LXUJCEl41OTKcfi9uKymXnuc9bteSshgnhklKQDKFZ0xB2MmT1XOBmElOhpCd8/SNAmmZu6sf2PRj0uNLOs15oAlX0ioQ4hFy2BxqJG2pMGFdW+8wW5y1GCR1/qfI6RjxWAdwC2r8I8OYEGJGodF247OiFY1DDNiS9dUqpsVUWp64+ZdYqh2DqBiOI2ubaNdIYlN3al6HR9wIbbH82sj2wa908/nB2nsAR/5PXi5aW3b2N5G75TpsdNrnXIEJ7pd6sniyPpuf9WBnqWT24dFiriHi2t/7NvYkBaLDPAPcrJeir0gRqwqWS/NuMCtM3MlT1X5WSi08tEIcY8VTWD3tI7RALYiKFWDKSug29YO7gEkIqrOu9KhAess9rx93bWXDJLlcCODmcRqc1YQ/aeBJ/L4d6/hrPGmyBiex7cw0SnjD1zn2I0BTfWuLiRB+wj6HdfqwRn+IH4/uW4V4wZhoDcAPGlx2efjn6M9nKiElaFl7iKmZ2hUV/8iDURelnBhjQGHjIRY2jEPIeLd6hLYlR3l38E0Rkjd1xsGHrf3JYB3yh6jra1rfiiTCleDCyPFaLdL5EFr6QaaX3ffNOkd+H/Xs/WvJ0lGzHFtambt0bcpX3FkzmQW1W6A9Iyb73PmX9L+EEMtqpOs8Nxqh2mbvRygircJwAZ6p9U5m64=
    app: dry-plains-15881