language: java
jdk:
- openjdk15
sudo: false
install: true
script: mvn clean package -DskipTests=true
services:
- postgresql
before_install:
- psql -c 'create database forum;' -U postgres
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: oggen18@gmail.com
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN="f4e6786c-51bb-4cdb-b42c-6a65623e46fd"
deploy:
  provider: heroku
  api_key:
    secure: lHFC5Jm8VqCzqjP9mMwsPON7Em75C1hoY6ePe7V2flKG45YF/SNR5zk1iJ5R/ZKuOLbIP9j4VfWPc2Mlei+3jnaQbGVtjQOv5HlnTMBlWul6BGXgUIp+DJUvAWvqjhYRixR0FPVaWoirslbuDzN6a5MWV/nV8bB5xcxvG3O3ZTkriAvzvBaR2ZDLiPLHcKXMSPMqaqzTYMuVvLhqcMFanzxo1I6yNw9EoTrYozmUsdL5B0M9KW2vZhH7nXiRr8KhpXPzlz4OnElAnmu2tXf7diTq1Gypq3z6Vl5UKY+CqfEzgxWcQst+5ZJLgiwZMDr13nTdBabKIXUowZmNQwU1vWG3kcPrPjU35vjZnUF50KDUkkKobPNoPrt+epG20/F+P9wj75i4qtIT0ad4VTK0eTHz4AAFm9yyalJh9dfpc5KemwjHytzy+gBJb3e8FLx1liOzKdi0CPQiqEs0TNcqi1AVEq+ETZNZcHAl9ktrYSjbxgf/YdqALvaYFiJszT3U0ehum0gyTqDGqrEzECdmx8qhBsvtPvn1aY4e0kNdTmFXwwgwF8JF4nRkadzkifn5DNaWN0fINlBmeimcE+JaSFFNgqdQggHzj1b7joAsTn+/zb+cVakCWEEE2uc25g1RsZTVHs7ru4CoPHzaaIup2HEnZDEP4rK4F1r8dyrBkkI=
  app: dry-plains-15881