language: java
jdk:
- openjdk15
sudo: false
install: true
script: mvn clean package -DskipTests=true
services:
- postgresql
before_install:
- psql -c 'create database forum;' -U postgres
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients: oggen18@gmail.com
    on_success: never
    on_failure: always
env:
  global:
  - CODECOV_TOKEN="f4e6786c-51bb-4cdb-b42c-6a65623e46fd"
deploy:
  provider: heroku
  api_key:
    secure: USjd680Xz+aH4Pcmb5wl3gtQNsTxvVUR6zVP0qDG1jgNxB/uMMpLF7iNgYW0Tmp2K+3ihzNHSvOj5BgOohelgCMpN2Zg7CQ4QqqmuigZN2X9qSmlfNA1KRpt8qxtB0rWtqB9P0zW2uuW26Tqv1MYx2c8uJIQtjBwswJhXYc7knAQPMwV5i4SO0LBIBcTd/4zd5C2WDg2fTz9RxXsn9+kMID9W9o9QN1jm3i/3I5MyQqiSlhQF8le4uiQZBYkElPxjZMJGXurZvAC8t5+z6ZYlD5IkpwNp3VVxMwvEH4TLR1+XTHhfzaxvstmJ2H/wozulXT5ZEolncpAYzNeNa2uAcD69QiPJlZovKmoYyKwMLAwMB2w44p9qFgD/tGG8P8qooTJ1lGoQL4Bm785/q6irvmE/Fx/qI0VEupbLOKlnp1tmRimaeiNxLB1U0Q5zFV5YceGe1Ry49XBDA3BjcPcI/6QEpcUS1YMfSUqCFFT7keFbe5yRy1A4ExrosvZqadX5jwSsdYFeDt4A+Xpqe0KL8XPmHtkbz+SsTt3cadatwn+BW+kh+mXJ/oqHda/cVxRVzSvC7qrGa8PjjN6+7BW8xK1G8bUqHE3An0zIRQk1xN1b7t9JxOCPh9HfThGdVbGSAedRVARe25YgLHmgl3Lg0mNfSyL1rngPP2uBi64c9s=
    app: dry-plains-15881